from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    observer = Node(
        package="mbam_gazebo_tracking",
        executable="limo_observer",
        output="screen",
        parameters=[
            {
                "robot_name": LaunchConfiguration("robot_name"),
                "report_topic": LaunchConfiguration("report_topic"),
                "odom_topic": LaunchConfiguration("odom_topic"),
                "image_topic": LaunchConfiguration("image_topic"),
                "camera_info_topic": LaunchConfiguration("camera_info_topic"),
                "scan_topic": LaunchConfiguration("scan_topic"),
                "report_period_sec": LaunchConfiguration("report_period_sec"),
                "world_frame": LaunchConfiguration("world_frame"),
                "camera_height_m": LaunchConfiguration("camera_height_m"),
                "camera_pitch_rad": LaunchConfiguration("camera_pitch_rad"),
                "camera_forward_offset_m": LaunchConfiguration("camera_forward_offset_m"),
                "camera_lateral_offset_m": LaunchConfiguration("camera_lateral_offset_m"),
                "target_ground_z_m": LaunchConfiguration("target_ground_z_m"),
                "min_ground_range_m": LaunchConfiguration("min_ground_range_m"),
                "max_ground_range_m": LaunchConfiguration("max_ground_range_m"),
                "enable_scan_fusion": LaunchConfiguration("enable_scan_fusion"),
                "scan_window_half_width": LaunchConfiguration("scan_window_half_width"),
                "scan_min_valid_range_m": LaunchConfiguration("scan_min_valid_range_m"),
                "scan_range_gate_m": LaunchConfiguration("scan_range_gate_m"),
                "enable_people_detection": LaunchConfiguration("enable_people_detection"),
                "enable_robot_detection": LaunchConfiguration("enable_robot_detection"),
                "yolo_model_path": LaunchConfiguration("yolo_model_path"),
                "yolo_device": LaunchConfiguration("yolo_device"),
                "lower_body_crop_top_fraction": LaunchConfiguration("lower_body_crop_top_fraction"),
                "people_confidence_threshold": LaunchConfiguration("people_confidence_threshold"),
                "robot_min_area_px": LaunchConfiguration("robot_min_area_px"),
                "max_detections": LaunchConfiguration("max_detections"),
                "aruco_dictionary": LaunchConfiguration("aruco_dictionary"),
            }
        ],
    )
    safety_controller = Node(
        package="mbam_gazebo_tracking",
        executable="limo_safety_controller",
        output="screen",
        parameters=[
            {
                "robot_name": LaunchConfiguration("robot_name"),
                "scan_topic": LaunchConfiguration("scan_topic"),
                "input_cmd_topic": LaunchConfiguration("input_cmd_topic"),
                "output_cmd_topic": LaunchConfiguration("output_cmd_topic"),
                "control_period_sec": LaunchConfiguration("safety_control_period_sec"),
                "cmd_timeout_sec": LaunchConfiguration("cmd_timeout_sec"),
                "scan_timeout_sec": LaunchConfiguration("scan_timeout_sec"),
                "stop_on_missing_scan": LaunchConfiguration("stop_on_missing_scan"),
                "min_valid_range_m": LaunchConfiguration("safety_min_valid_range_m"),
                "max_linear_speed_mps": LaunchConfiguration("max_linear_speed_mps"),
                "max_angular_speed_rps": LaunchConfiguration("max_angular_speed_rps"),
                "forward_emergency_stop_distance_m": LaunchConfiguration("forward_emergency_stop_distance_m"),
                "forward_slowdown_distance_m": LaunchConfiguration("forward_slowdown_distance_m"),
                "reverse_emergency_stop_distance_m": LaunchConfiguration("reverse_emergency_stop_distance_m"),
                "reverse_slowdown_distance_m": LaunchConfiguration("reverse_slowdown_distance_m"),
                "turn_clearance_distance_m": LaunchConfiguration("turn_clearance_distance_m"),
                "side_clearance_distance_m": LaunchConfiguration("side_clearance_distance_m"),
                "escape_turn_speed_rps": LaunchConfiguration("escape_turn_speed_rps"),
            }
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument("robot_name", default_value="limo0"),
            DeclareLaunchArgument("report_topic", default_value="/mbam/robot_reports"),
            DeclareLaunchArgument("odom_topic", default_value="/odom"),
            DeclareLaunchArgument("image_topic", default_value="/camera/color/image_raw"),
            DeclareLaunchArgument("camera_info_topic", default_value="/camera/color/camera_info"),
            DeclareLaunchArgument("scan_topic", default_value="/scan"),
            DeclareLaunchArgument("input_cmd_topic", default_value=""),
            DeclareLaunchArgument("output_cmd_topic", default_value="/cmd_vel"),
            DeclareLaunchArgument("report_period_sec", default_value="0.25"),
            DeclareLaunchArgument("safety_control_period_sec", default_value="0.05"),
            DeclareLaunchArgument("cmd_timeout_sec", default_value="0.5"),
            DeclareLaunchArgument("scan_timeout_sec", default_value="0.5"),
            DeclareLaunchArgument("stop_on_missing_scan", default_value="true"),
            DeclareLaunchArgument("safety_min_valid_range_m", default_value="0.15"),
            DeclareLaunchArgument("max_linear_speed_mps", default_value="0.6"),
            DeclareLaunchArgument("max_angular_speed_rps", default_value="1.2"),
            DeclareLaunchArgument("forward_emergency_stop_distance_m", default_value="0.45"),
            DeclareLaunchArgument("forward_slowdown_distance_m", default_value="0.90"),
            DeclareLaunchArgument("reverse_emergency_stop_distance_m", default_value="0.30"),
            DeclareLaunchArgument("reverse_slowdown_distance_m", default_value="0.60"),
            DeclareLaunchArgument("turn_clearance_distance_m", default_value="0.35"),
            DeclareLaunchArgument("side_clearance_distance_m", default_value="0.28"),
            DeclareLaunchArgument("escape_turn_speed_rps", default_value="0.55"),
            DeclareLaunchArgument("world_frame", default_value="map"),
            DeclareLaunchArgument("camera_height_m", default_value="0.32"),
            DeclareLaunchArgument("camera_pitch_rad", default_value="0.30"),
            DeclareLaunchArgument("camera_forward_offset_m", default_value="0.0"),
            DeclareLaunchArgument("camera_lateral_offset_m", default_value="0.0"),
            DeclareLaunchArgument("target_ground_z_m", default_value="0.0"),
            DeclareLaunchArgument("min_ground_range_m", default_value="0.35"),
            DeclareLaunchArgument("max_ground_range_m", default_value="8.0"),
            DeclareLaunchArgument("enable_scan_fusion", default_value="true"),
            DeclareLaunchArgument("scan_window_half_width", default_value="2"),
            DeclareLaunchArgument("scan_min_valid_range_m", default_value="0.20"),
            DeclareLaunchArgument("scan_range_gate_m", default_value="2.0"),
            DeclareLaunchArgument("enable_people_detection", default_value="true"),
            DeclareLaunchArgument("enable_robot_detection", default_value="true"),
            DeclareLaunchArgument("yolo_model_path", default_value=""),
            DeclareLaunchArgument("yolo_device", default_value=""),
            DeclareLaunchArgument("lower_body_crop_top_fraction", default_value="0.35"),
            DeclareLaunchArgument("people_confidence_threshold", default_value="0.35"),
            DeclareLaunchArgument("robot_min_area_px", default_value="250"),
            DeclareLaunchArgument("max_detections", default_value="12"),
            DeclareLaunchArgument("aruco_dictionary", default_value="DICT_4X4_50"),
            observer,
            safety_controller,
        ]
    )
